all:
  children:
    monitored_servers:
      hosts:
        SRV-Collecte:
          ansible_host: srvcollecte.ads.local # IP de SRV-Collecte
        Casaos:
          ansible_host: casaos.ads.local # IP de CasaOS
        # Ajoute tes autres serveurs ici
        Adguard-DHCP:
          ansible_host: 172.16.12.5 # IP de Adguard
        pdm:
          ansible_host: pdm.ads.local # IP de PDM
        pbs:
          ansible_host: pbs.ads.local # IP de PBS
        ia-ollama-jde:
          ansible_host: ollama.ads.local # IP de ia-ollama-jde
        ia-librechat-jde:
          ansible_host: librechat.ads.local # IP de ia-librechat-jde
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: /home/julien/.ssh/id_ed25519
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
